app:
  version: '1.0.0'
  port: 9000
  moment:
    format: 'DD/MM/yyyy HH:mm:ss'
    tz: 'America/Bogota'

logging:
  level: info
  directory: logs/
  hostnameAsFileName: false
  filename: apitransaction.log
  transport:
    console: true
    file: false

db:
  yapechallenge:
    mongo: 
      url: mongo:27017
      database: yapechallenge
      collection:
        transactions: transactions

kafka:
  url: broker
  port: 29092
  bindings:
    topicName:
      sendTransactionCreated: 'sendTransactionCreated'
      sendTransactionStatusApproved: 'sendTransactionStatusApproved'
      sendTransactionStatusRejected: 'sendTransactionStatusRejected'