app:
  version: '1.0.0'
  port: 9000
  moment:
    format: 'DD/MM/yyyy HH:mm:ss'
    tz: 'America/Bogota'

logging:
  level: info
  directory: logs/
  hostnameAsFileName: false
  filename: criptoinvestment.log
  transport:
    console: true
    file: false

db:
  yapechallenge:
    mongo: 
      url: 66.94.120.188:27017
      database: yapechallenge
      collection:
        transactions: transactions

kafka:
  clientId: ''
  url: ''
  port: ''
  bindings:
    topicName:
      sendTransactionCreated: 'sendTransactionCreated'
      sendTransactionStatusApproved: 'sendTransactionStatusApproved'
      sendTransactionStatusRejected: 'sendTransactionStatusRejected'
    groupId:
      yapeFlow: 'yapeFlow'